version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    environment:
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_VHOST

  mongodb:
    image: mongo:latest
    hostname: "mongodb"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE

  server:
    build: ./server
    image: chat_poc_server
    ports:
      - "3001:3000"
    depends_on:
      - rabbitmq
    working_dir: /app/server
    volumes:
      - ./server:/app/server
      - ./server/.env:/app/.env
    links:
      - rabbitmq
      - mongodb
    command: nodemon bin/www --ignore node_modules
    environment:
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB=${MONGO_INITDB_DATABASE}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - JWT_SECRET



